### ISSUE TITLE
I can not install Qwinff in Ubuntu15.10 !

### ISSUE THREAD

**Issue by taijuin** [qwinff/qwinff#10]
just this "libavcodec-extra-56"
![123](https://cloud.githubusercontent.com/assets/1614551/11182561/a4c37972-8ca6-11e5-876a-3469c457db4f.png)

**Comment by lzh9102** [comment]
Hello,

I updated the package on launchpad and now it works with Ubuntu 15.10. Please try installing it again by `sudo apt-get update && sudo apt-get install qwinff` and see if there is any problems. Thanks

**Comment by taijuin** [comment]
Yes, it has been no problem. Thank you...

**Comment by anewuser** [comment]
@lzh9102 Have you submitted qwinff to be added to the official Debian/Ubuntu repositories yet?

**Comment by lzh9102** [comment]
No, but I would appreciate if anyone could submit qwinff to debian or ubuntu.

**Comment by anewuser** [comment]
https://bugs.launchpad.net/ubuntu/+bug/1616172
