### ISSUE TITLE
Copy Video No Re Encoding?

### ISSUE THREAD

**Issue by Geyup** [qwinff/qwinff#13]
First let me say thank you for this project, I hope this continues on for many years, qwinff is very nice.

I was looking over the application and I don't see the ability to just copy the video only, not re-encode it.

Many times I only want to adjust volume like this;

`ffmpeg -i inputfile -vcodec copy -af "volume=15dB" outputfile`

Can I do the same with qwinff?

thank you

**Comment by lzh9102** [comment]
This is currently not possible with qwinff, but I think it can be done with some minor modifications. What I am planning is to add a *Copy Video* option next to *Disable Video*. If the former is checked, qwinff will invoke `ffmpeg` with `-vcodec copy` and omit all other video options.

![20160817_091834](https://cloud.githubusercontent.com/assets/1400062/17721311/e0b14be8-645b-11e6-9bd6-32068a0e341a.png)

How do you think about this?

**Comment by Geyup** [comment]
Ok...

**Comment by lzh9102** [comment]
Added options to copy video/audio in commit ccd1e5336bf1e6ffbc5be3cf5f67d6e7702e4f19.
