### ISSUE TITLE
suport stream to facebook

### ISSUE THREAD

**Issue by zodman** [qwinff/qwinff#14]
ffmpeg -re -i file.flv -codec copy -f flv rtmp://live.twitch.tv/app/<stream key>

let im way to introduce a destination file, introduce a stream url like rtmp

**Comment by lzh9102** [comment]
QWinFF is designed to be a "media file converter" application. Although ffmpeg can do lots of things like streaming to a url, supporting them in qwinff will require substantial re-design of the application. Please consider using another application like [FFMPEG Stream Creation GUI](https://sourceforge.net/projects/ffmpegstreamgui/) for streaming with ffmpeg.
