### ISSUE TITLE
Flattr donation

### ISSUE THREAD

**Issue by orschiro** [qwinff/qwinff#3]
Hi all,

Great piece of software! 

Can I donate to your project using flattr?

Warmly,

Robert

**Comment by lzh9102** [comment]
Hi,

Thanks a lot for your interest in this project!
I just created a flattr page at https://flattr.com/thing/527ecc43ad101eb0840f37f9e165e681. Your support is appreciated.

Best wishes,
Che-Huai

**Comment by orschiro** [comment]
Thanks Che-Huai!

I love to support your project!

You might also want to place the flattr button on the project website or Github to make it more visible.

Warmly,

Robert
