### ISSUE TITLE
Port to Qt5?

### ISSUE THREAD

**Issue by s8321414** [qwinff/qwinff#5]
Maybe this program can be ported to Qt5, it will be good and more modern.

**Comment by lzh9102** [comment]
Hello,

I think it is a good idea to make qwinff compatible to Qt5, but I still want to support Qt4 because some legacy systems I'm using only come with Qt4. I'll see if it is possible to support Qt4 and Qt5 at the same time (maybe using preprocessor directives like `#ifdef`).

**Comment by s8321414** [comment]
:smile:

**Comment by lzh9102** [comment]
Now qwinff can be compiled with Qt5 (changeset https://github.com/qwinff/qwinff/commit/a81459672ce7b6ce5ecc341cb619c6aa0edc5e4c).

**Comment by s8321414** [comment]
Great!
