### ISSUE TITLE
希望可以更新 Ubuntu 軟體包！

### ISSUE THREAD

**Issue by taijuin** [qwinff/qwinff#6]
這個程式很棒，簡單易用！希望可以持續更新 ...

以下的PPA源似乎不適用 Ubuntu15.04，希望可以更新....感謝～
https://launchpad.net/~lzh9102/+archive/ubuntu/qwinff

用來將數位攝影機的MTS檔轉為MP4檔蠻方便的！

**Comment by lzh9102** [comment]
沒問題，我有空就把它更新到 14.10 和 15.04。
感謝您的支持！

**Comment by lzh9102** [comment]
已經在 launchpad 上建置 15.04 版的 package，現在應該可以安裝了。如果有錯請回報。

安裝步驟:

```
sudo apt-add-repository ppa:lzh9102/qwinff
sudo apt-get update
sudo apt-get install qwinff
```
