### ISSUE TITLE
Preview video with mpv?

### ISSUE THREAD

**Issue by maz-1** [qwinff/qwinff#8]
mpv is a video player based on mplayer and mplayer2, which supports more features.

**Comment by lzh9102** [comment]
QWinFF uses the [slave mode](http://www.mplayerhq.hu/DOCS/tech/slave.txt) interface to communicate to mplayer. Slaved mode is removed in mpv so it would be difficult to embed mpv inside QWinFF.

If embedding is not required, it would be easy to just invoke mpv to play the video. Currently previewing by ffplay is done in this way.

**Comment by maz-1** [comment]
I see, thanks anyway
